import { Random } from './Random.js';
import { type IBonusState, type IFreeSpinBonus, type IPickBonus, type ISpinResponseData } from './types.js';

export class BonusManager {
  private rng: Random;
  private bonusState: IBonusState | null = null;

  constructor(rng: Random) {
    this.rng = rng;
  }

  /**
   * Check if a spin result should trigger a bonus.
   * This is a simple example: trigger on 3+ scatter symbols (e.g., symbol ID 9).
   */
  checkTrigger(result: number[][]): { triggered: boolean; data?: any } {
    const scatterId = 9;
    let count = 0;
    for (const row of result) {
      for (const symbol of row) {
        if (symbol === scatterId) count++;
      }
    }
    if (count >= 3) {
      return {
        triggered: true,
        data: { scatterCount: count, freeSpins: count * 2 },
      };
    }
    return { triggered: false };
  }

  /**
   * Start a free spin bonus.
   */
  startFreeSpins(spins: number, multiplier: number = 1, bet: number): IFreeSpinBonus {
    this.bonusState = {
      type: 'freespin',
      spinsRemaining: spins,
      multiplier,
      totalWin: 0,
      bet,
    };
    return this.bonusState as IFreeSpinBonus;
  }

  /**
   * Start a pick bonus (e.g., pick items for prizes).
   */
  startPickBonus(items: { id: string; label: string; value: number }[]): IPickBonus {
    this.bonusState = {
      type: 'pick',
      items,
      pickedIds: [],
      totalWin: 0,
    };
    return this.bonusState as IPickBonus;
  }

  /**
   * Process a pick action.
   */
  pickItem(itemId: string): { win: number; remaining: IPickBonus['items'] } {
    const state = this.bonusState;
    if (!state || state.type !== 'pick') {
      throw new Error('No active pick bonus');
    }
    const item = state.items.find(i => i.id === itemId);
    if (!item) throw new Error('Invalid item');
    if (state.pickedIds.includes(itemId)) throw new Error('Item already picked');

    state.pickedIds.push(itemId);
    state.totalWin += item.value;
    const remaining = state.items.filter(i => !state.pickedIds.includes(i.id));
    return { win: item.value, remaining };
  }

  /**
   * Process a free spin: deduct one spin, return the spin result.
   * The spin result is generated by the SpinEvaluator, but we need to apply the multiplier.
   */
  processFreeSpin(spinResult: Omit<ISpinResponseData, 'balanceAfter'>): Omit<ISpinResponseData, 'balanceAfter'> & { spinsRemaining: number } {
    const state = this.bonusState;
    if (!state || state.type !== 'freespin') {
      throw new Error('No active free spin bonus');
    }
    if (state.spinsRemaining <= 0) {
      throw new Error('No free spins remaining');
    }

    state.spinsRemaining--;
    // Multiply the win by the bonus multiplier
    const multiplier = state.multiplier || 1;
    const totalWin = (spinResult.totalWin || 0) * multiplier;
    state.totalWin += totalWin;

    // Return the spin result with updated totalWin
    return {
      ...spinResult,
      totalWin,
      spinsRemaining: state.spinsRemaining,
    };
  }

  /**
   * Check if a bonus is active.
   */
  isActive(): boolean {
    return this.bonusState !== null && (
      (this.bonusState.type === 'freespin' && this.bonusState.spinsRemaining > 0) ||
      (this.bonusState.type === 'pick' && this.bonusState.items.length > this.bonusState.pickedIds.length)
    );
  }

  /**
   * Get the current bonus state.
   */
  getState(): IBonusState | null {
    return this.bonusState;
  }

  /**
   * End the current bonus.
   */
  endBonus(): void {
    this.bonusState = null;
  }
}